### ISSUE TITLE
Erro ao importar arquivo XML de NFE

### ISSUE THREAD

**Issue by chrmorais** [thiagopena/djangoSIGE#10]
Quando tento importar um arquivo xml de NFe o sistema gera a mensagem de erro:
...  djangosige/apps/fiscal/views/nota_fiscal.py", line 522, in post
    processador_nota = ProcessadorNotaFiscal()
NameError: name 'ProcessadorNotaFiscal' is not defined

Como posso corrigir isso?

**Comment by thiagopena** [comment]
@chrmorais, para a emissão de NF-e é necessário instalar o [PySIGNFe](https://github.com/thiagopena/PySIGNFe).

**Comment by chrmorais** [comment]
@thiagopena, Valeu pela ajuda! 
Instalei a biblioteca PySIGNFe o erro foi sanado e parece que está processando o xml corretamente.
O sistema já pode ser colocado em produção? Alguma recomendação para deploy?
grato!

**Comment by chrmorais** [comment]
@thiagopena, Valeu pela ajuda! 
Instalei a biblioteca PySIGNFe o erro foi sanado e parece que está processando o xml corretamente.
O sistema já pode ser colocado em produção? Alguma recomendação para deploy?
grato!

**Comment by thiagopena** [comment]
@chrmorais, o sistema pode sim ser usado em produção, mas aconselho testar bem as implementações que for usar antes de utiliza-las em produção, principalmente a emissão de NF-e que pode estar desatualizada.
Abs.

**Comment by chrmorais** [comment]
Certo, vou continuar os testes.
