### ISSUE TITLE
Ao clicar no ícone Ajuda falta a target blank

### ISSUE THREAD

**Issue by nilton-medeiros** [thiagopena/djangoSIGE#103]
Eu alterei o arquivo base.html na linha 73 e acrescentei a target="_blank" para que ao clicar no ícone de Ajuda não abrisse o novo link sobre o sistema em uso.
De:   `<li><a href="https://github.com/thiagopena/djangoSIGE" title="Ajuda" ><i class="material-icons">&#xE8FD;</i></a></li>`
Para: `<li><a href="https://github.com/thiagopena/djangoSIGE" target="_blank" title="Ajuda" ><i class="material-icons">&#xE8FD;</i></a></li>`
Não fiz um Push do meu Fork porque não manjo muito de gitHub e acho que meu Fork está desatualizado com o main.

**Comment by rg3915** [comment]
Feito @nilton-medeiros
