### ISSUE TITLE
Erro na emissão de NFe

### ISSUE THREAD

**Issue by chrmorais** [thiagopena/djangoSIGE#11]
Estou realizando testes e estou recebendo a tela de erro na emissão de NFe:

Request Method: | POST
-- | --
http://localhost:8000/fiscal/notafiscal/emitir/6/
1.11.6
OSError
Error reading file '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages/pysignfe/nfe/manual_600/schema/PL_008i2/consSitNFe_v3.10.xsd': failed to load external entity "/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages/pysignfe/nfe/manual_600/schema/PL_008i2/consSitNFe_v3.10.xsd"
/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages/pysignfe/xml_sped/base.py in validar, line 880
/home/chrmorais/SolluxLabs/djSIGE/venv/bin/python
3.5.3
['/home/chrmorais/SolluxLabs/djSIGE',  '/home/chrmorais/SolluxLabs',  '/home/chrmorais/SolluxLabs/djSIGE',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python35.zip',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages/PySIGNFe-0.1.0-py3.5.egg']
Sex, 13 Out 2017 13:55:29 -0300

**Comment by thiagopena** [comment]
@chrmorais, não estou conseguindo reproduzir este erro, ele está ocorrendo ao tentar abrir o arquivo do schema xml do PySIGNFe, verifique as configurações de permissão, ou como o python está acessando as informações dos arquivos na pasta: ```/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages/pysignfe/nfe/manual_600/schema/PL_008i2/```

**Comment by chrmorais** [comment]
@thiagopena, Agora que você mencionou eu conferi aqui e na minha instalação não existe a pasta schema/PL_008i2/
Não sei o que ocorreu. Vou refazer os passos da instalação e retorno o resultado. valeu!

**Comment by chrmorais** [comment]
Ok! Após reinstalar a biblioteca pysignfe o problema foi corrigido. 
Está gerando e assinando o xml, também o danfe está sendo criado de acordo.
Agradeço a ajuda.

**Comment by thiagopena** [comment]
@chrmorais , ótima notícia, qualquer problema ou bug pode abrir um Issue ou perguntar por e-mail que fico feliz em ajudar. Abs.
