### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by chrmorais** [thiagopena/djangoSIGE#12]
Request Method: | POST
-- | --
http://localhost:8000/fiscal/notafiscal/consultarnota/10/
1.11.6
SSLError
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)
/usr/lib/python3.5/ssl.py in do_handshake, line 641
/home/chrmorais/SolluxLabs/djSIGE/venv/bin/python
3.5.3
['/home/chrmorais/SolluxLabs/djSIGE',  '/home/chrmorais/SolluxLabs',  '/home/chrmorais/SolluxLabs/djSIGE',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python35.zip',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/plat-x86_64-linux-gnu',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/lib-dynload',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages',  '/home/chrmorais/SolluxLabs/djSIGE/venv/lib/python3.5/site-packages/PySIGNFe-0.1.0-py3.5.egg']
Qua, 18 Out 2017 22:01:13 -0200

**Comment by thiagopena** [comment]
@chrmorais , esse erro é problema do certificado A1, é provável que seu certificado seja inválido para emissão.

**Comment by chrmorais** [comment]
Vou verificar com o Contador. Blz!
