### ISSUE TITLE
Não consigo rodar o projeto. 

### ISSUE THREAD

**Issue by walneialbuquerque** [thiagopena/djangoSIGE#120]
Boa noite! baixei o projeto porém não consigo rodar ele, alguém poderia me ajudar ?

**Comment by rg3915** [comment]
Ola @walneialbuquerque seja mais específico por favor. Qual foi o erro? O que que deu errado?

**Comment by walneialbuquerque** [comment]
Foram vários,  tentei de todas as formas.  Seria possível alguém me auxiliar em acesso remoto? Sou estudante iniciante da linguagem e me interessei pelo projeto  . Ótima iniciativa de quem fez

**Comment by nilton-medeiros** [comment]
Siga as instruções mais detalhadas nesse link fork :https://github.com/nilton-medeiros/djangoSIGEObter o Outlook para AndroidDe: walneialbuquerque ***@***.***>Enviado: sexta-feira, 15 de outubro de 2021 00:29Para: thiagopena/djangoSIGECc: SubscribedAssunto: Re: [thiagopena/djangoSIGE] Não consigo rodar o projeto.  (#120)

Foram vários,  tentei de todas as formas.  Seria possível alguém me auxiliar em acesso remoto? Sou estudante iniciante da linguagem e me interessei pelo projeto  . Ótima iniciativa de quem fez

**Comment by walneialbuquerque** [comment]
O meu deu problema com esse requerimento Geraldo. Como faço a instalação dele?

**Comment by walneialbuquerque** [comment]
Obg pelo suporte. consegui rodar o projeto, vi alguns comentários e consegui resolver.

**Comment by rg3915** [comment]
@nilton-medeiros obrigado pela ajuda. Não sabia desse problema com algumas libs. Vou ver se consigo resolver isso... valeu.
