### ISSUE TITLE
Erro ao alterar dados das pessoas

### ISSUE THREAD

**Issue by flaudemir79** [thiagopena/djangoSIGE#14]
![captura de tela 2017-11-16 as 19 54 04](https://user-images.githubusercontent.com/925561/32920614-b4857980-cb08-11e7-912e-dd59a10a6a01.png)

Já tentei debugar e encontrar o local exato do erro e ainda não identifiquei.

**Comment by thiagopena** [comment]
Bom dia @flaudemir79, esse erro ocorre ao tentar modificar os dados do POST na view de clientes. Então este commit corrige o problema: https://github.com/thiagopena/djangoSIGE/commit/b7b78a9282e2a4ee776020f83812e3abd437467b
Mas mesmo assim, recomendo utilizar a versão 1.10.1 do Django com o SIGE por enquanto, pois ao atualizar para a versão 1.11.7 outros problemas podem ocorrer, no futuro vejo se consigo fazer a atualização para a versão mais nova.
Obrigado.

**Comment by flaudemir79** [comment]
Parabéns pelo código!
