### ISSUE TITLE
Estoque fica incorreto se for editar um documento.

### ISSUE THREAD

**Issue by CoutinhoElias** [thiagopena/djangoSIGE#15]
Bom dia amigos!
Vi seu projeto no github e achei fantástico!
Vi como vocês simplificaram a movimentação de estoque usando signals.
Minha observação é a seguinte:

Supondo que eu crie um pedido e transforme em nota ele movimentaria o estoque. Ótimo, faz isso certinho.

Agora suponha que eu fiz alguma coisa errada nessa nota e preciso alterar a quantidade do item que de alguma maneira fiz errado. Neste momento o sistema vai dar saída novamente das quantidades, ou seja, o estoque ficará errado.

Amigos, estou aprendendo django e tomei seu código como modelo para mim. Minha sugestão é meramente baseada em usabilidade e com a intenção de ver a sua solução para que eu possa aprender com vocês.

Espero sua compreensão e se corrigir por favor me avisa, gostaria muito de aprender como vocês fizeram. 

Abraço.

**Comment by thiagopena** [comment]
Obrigado pela sugestão Elias, isso realmente é um bug e deve ser corrigido. Assim que tiver tempo faço as correções necessárias, provavelmente irei remover o uso de signals e passar essa lógica para as views.
Abs.

**Comment by thiagopena** [comment]
@CoutinhoElias o problema foi corrigo nesse [commit](https://github.com/thiagopena/djangoSIGE/commit/c1c988f72ace8f040c30e74a7eb80afae843bbd7)
Aqui estou dando a opção para o usuário de remover movimentações de estoque. 
No caso ele teria que remover o pedido de compra/venda antigo e remover a movimentação de estoque gerada por esse pedido, assim o estoque é atualizado.
Se puder testar e verificar se é isso mesmo ficaria grato 😄 
vou fechar a issue, pode abrir outra caso encontre um problema ou comentar nessa mesma issue que reabro ela.

Abs.
