### ISSUE TITLE
Definir a versão dos pre-requisitos mais claramente

### ISSUE THREAD

**Issue by ceccarelli** [thiagopena/djangoSIGE#17]
Tentei rodar com Python 3.x e Django 2.x e teve milhões de inconsistências, depois de corrigir tudo descobri que o Geraldo simplesmente não roda em Python 3.x. Desisti e tive que voltar para o Python 2.x e o Django 1.x...

Acho que instruções com avisos claros de que não funciona em versões mais recentes ajudariam os mais inexperientes a colocar o sistema de pé com mais facilidade... e poupariam o trabalho no caso dos cabeça-duras como eu. ;-)

**Comment by aykou** [comment]
Eita, já ia me juntar ao projeto, estou aprender django e estava procurando projetos e acabei parando aqui, mas quero usar python 3.5+ e django 2+, lamentavel, gostei muito desse.

**Comment by ceccarelli** [comment]
O problema nem é o Sige que é fácil de ajustar... O problema que vejo é
portar o Geraldo.

Em 4 de jan de 2018 4:02 PM, "aykou" <notifications@github.com> escreveu:

**Comment by aykou** [comment]
Mas o Geraldo é só para gerar PDF não é? Além do mais ele tem mais de 5 anos desde a ultima atualização, deve haver algo novo.
Mesmo assim você não acha interessante, caso não haja nada compatível para as versões atuais de python/django escrever um app que faça isso e integra-lo nativamente a esse projeto?

**Comment by thiagopena** [comment]
@ceccarelli, concordo que estão faltando alguns avisos quanto ao sistema, no caso do Geraldo, tem um fork meu que (acredito eu hehe) funciona com o python 3.x: https://github.com/thiagopena/geraldo. Meu erro foi ter deixado o link do geraldo do marinho, ao invés de deixar o meu fork.

No caso do Django, outro problema é que quando escrevi o requirements deixei: Django>=1.10.1 quando deveria ter deixado Django==1.10.1, isso causou muitos problemas para usuários pós Django 2.0 pois o sistema ainda não porta com essa nova versão do Django.

Vou atualizar o README para facilitar a vida dos usuários.

Obrigado.

**Comment by thiagopena** [comment]
@aykou sim, o Geraldo é usado para geração de DANFE, DANFCE e relatórios em PDF. Peço que utilize o meu fork do geraldo: https://github.com/thiagopena/geraldo

**Comment by aykou** [comment]
@thiagopena As alterações necessárias para django 2 são muito extensas? você não acha interessante atualizar? Quero usar e ajudar a aperfeiçoar esse projeto, mas desejo realmente me manter relativamente atualizado.
Quero adicionar:
PDV
Relatório o mais detalhado possível
Sinalizar quando o produto ficou muito tempo sem vender para determinar ações para o mesmo (promoções alteração de loja caso haja filiais e etc)
E muitas outras funções.
Só por curiosidade você pretende ainda melhorar esse projeto ou já chegou no ponto que você queria?

**Comment by thiagopena** [comment]
@aykou ainda quero e vou melhorar o projeto. Acredito que não seja muito trabalhoso portar o SIGE para o Django 2.0, algo que vai acontecer mais cedo ou mais tarde. Meu problema esses dias é realmente a falta de tempo, minha lista de TODOS para o SIGE está bem extensa e vai bem além de modificar a versão do Django.
Todas as idéias ai são ótimas implementações que até já passaram pela minha cabeça, o que me falta não é vontade, é tempo.

**Comment by aykou** [comment]
Fico feliz em saber dos seus planos, enquanto isso vou estudar mais, que eu baixei o projeto e algumas coisas me assustaram muito, preciso estudar muito ainda...
Vou ficar acompanhando de perto.
