### ISSUE TITLE
RecursionError at /compras/gerarpdfpedidocompra/1/

### ISSUE THREAD

**Issue by eusowell** [thiagopena/djangoSIGE#19]
Apresenta este erro no momento de gerar o pdf.

Estou usando uma VENV

RecursionError at /compras/gerarpdfpedidocompra/1/
maximum recursion depth exceeded while calling a Python object

Request Method: | GET
-- | --
http://localhost:8000/compras/gerarpdfpedidocompra/1/
1.10.1
RecursionError
maximum recursion depth exceeded while calling a Python object
D:\Control\venv\lib\_weakrefset.py in __contains__, line 72
D:\Control\venv\Scripts\python.exe
3.6.3

**Comment by eusowell** [comment]
Ele ocorre com todos os pedidos mas, eu entendi o motivo do erro.
E por causa que tem uma pasta antes da pasta original e o caminho ficou
extenso.

Agradeço pelo resposta .

Em Ter, 10 de abr de 2018 08:21, Gerley Machado <notifications@github.com>
escreveu:

**Comment by Gerley** [comment]
Fico feliz que tenha conseguido solucionar o problema.

Um abraço @eusowell!

**Comment by victorpb** [comment]
@eusowell  como o problema foi solucionado irei fechar a issues

**Comment by eusowell** [comment]
Beleza

Em Ter, 10 de abr de 2018 08:47, Victor Pereira <notifications@github.com>
escreveu:
