### ISSUE TITLE
ignorar pasta de media de usuarios

### ISSUE THREAD

**Issue by HigorMonteiro** [thiagopena/djangoSIGE#2]
Seria ideia ignorar as medias dos usuários, no caso as imagens de perfil .

`djangosige/media/imagens/usuarios/`

**Comment by thiagopena** [comment]
Higor, as medias em imagens são parte do aplicativo, são imagens default para quem não upou uma imagem de perfil.

**Comment by HigorMonteiro** [comment]
@thiagopena não sei se fui claro, mais quando eu upar  a imagem do usuário, será criado uma pasta **usuários** como ja é definida no modelo, então quando eu fizer um `git push`  a pasta com as imagens subiram  para o repositório .

**Comment by thiagopena** [comment]
Ah sim, você está certo, erro meu. Obrigado Higor.

**Comment by HigorMonteiro** [comment]
@thiagopena por nada brother estamos aqui, vou ajudar no que eu puder rsrsr ;)
