### ISSUE TITLE
Cadastramento de informações

### ISSUE THREAD

**Issue by AyronRangel** [thiagopena/djangoSIGE#21]
Ao clicar em NOVO para cadastrar qualquer informação no banco (Empresa, Pessoa, Produto e entre outros) aparece a seguinte mensagem:

DjangoUnicodeDecodeError at /cadastro/empresa/adicionar/

'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128). You passed in <django.utils.functional.__proxy__ object at 0x7fadacaa3c10> (<class 'django.utils.functional.__proxy__'>)

**Comment by thiagopena** [comment]
@AyronRangel qual a versão do Python que está utilizando?

**Comment by AyronRangel** [comment]
Python 3.6

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by AyronRangel** [comment]
Perdão 2.7. Tentei utilizar o Python 3.6... mas esta aparecendo outro erro: 

![img-20180327-wa0011](https://user-images.githubusercontent.com/30760695/38034048-c921e708-3277-11e8-86b3-f420cb1b5768.jpeg)

**Comment by thiagopena** [comment]
por favor utilize o Python 3+, e a versão do Django 1.10, bem provável de ser esse o problema

**Comment by edilmarjunior** [comment]
Amigo oq significa esse erro? 

![screenshot_5](https://user-images.githubusercontent.com/19784639/38211872-41e68586-3692-11e8-95a9-33a38e47df4b.png)

**Comment by victorpb** [comment]
Erro de codificação do arquivo. Como está seu arquivo configs.py? tem caractere especial?

**Comment by Gerley** [comment]
Pessoal,

Este erro ocorre ao executar o projeto com o Python 2!

Os arquivos "djangosige\configs\configs.py" e "djangosige\apps\base\views_mixins.py" possuem caracteres especiais e não possui a marcação de utf-8 no inicio do arquivo, "# -*- coding: utf-8 -*-", exigida para Python 2.

Como a recomendação do projeto é o Python 3, esse problema não caracteriza um erro.
