### ISSUE TITLE
Requisitos do modulo "Fiscal"

### ISSUE THREAD

**Issue by Gerley** [thiagopena/djangoSIGE#23]
![capturar](https://user-images.githubusercontent.com/6254252/38384859-a1f10392-38e6-11e8-9c8e-9852b0f268fa.PNG)

Ao executar algumas funcionalidades do modulo Fiscal, ex. emitir nota, este erro é apresentado.

Ao analisar o código, verifiquei que as bibliotecas "OpenSSL", "pytz" e "lxml" são requeridas pelo modulo Fiscal. Após a instalação, o sistema voltou a funcionar normalmente.

Acho que seria interessante adicionar estas bibliotecas no arquivo "requirements.txt".

**Comment by thiagopena** [comment]
Sim, vou adicionar @Gerley . Se quiser pode fazer um PR com a adição que aceito também.
Obrigado!

**Comment by thiagopena** [comment]
Então @victorpb , mas realmente me parece mais prático adicionar essas libs no requirements do SIGE, para evitar esse tipo de erro, não acha?

**Comment by victorpb** [comment]
@thiagopena  acedito que iria processar duas vezes, como vc ta usando um fork proprio do PySIGNFe então tem o controle, adicionar ela ao projeto pode acontecer em erro no futuro, tipo fazer uma atualização do projeto e quebrar o sistema pq o PySIGNFE  usa uma antiga.

**Comment by victorpb** [comment]
Percebi aqui que quando dei um freeze no meu PR acabei jogando todas as dependências do geraldo e do PySIGNFe. KKKKKKK

Se for colocar no requirements.txt eu já coloquei. Mas o ideal seria não ter ela lá para não quebrar as libs usadas.
https://github.com/thiagopena/djangoSIGE/pull/22/commits/584f6b32e6c28b571a559589b24b5374b13aafa0#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by thiagopena** [comment]
Oh verdade kkkkk. Acho uma boa deixar ai mesmo viu.

**Comment by Gerley** [comment]
@victorpb, eu executei o comando "pip install -r requirements.txt" na pasta raiz do projeto djangoSIGE. O PySIGNFe foi instalado mas suas dependências não.
