### ISSUE TITLE
Integrar projeto com C.I

### ISSUE THREAD

**Issue by victtorvpb** [thiagopena/djangoSIGE#24]
Fazer a integração do projeto com alguma ferramenta de C.I para rodar os testes, por exemplo o Travis.

**Comment by lukasgarcya** [comment]
Criei um Pull Request para fazer esta integração

**Comment by Gerley** [comment]
Bacana, a integração esta funcionando! Infelizmente os testes não estão passando. A maioria dos erros são os relatados na #27.

**Comment by lukasgarcya** [comment]
Talvez fazer testes via PostgreSQL e SQLite

**Comment by victorpb** [comment]
@lukasgarcya  estava pensando nisso e colocar ele como banco indicado para produção e vamos colocando outros aos poucos.
