### ISSUE TITLE
Verificar testes do modulo financeiro com o PostgreSQL

### ISSUE THREAD

**Issue by victorpb** [thiagopena/djangoSIGE#27]
Consertar os testes do módulo financeiro que não estão passando

**Comment by Gerley** [comment]
![image](https://user-images.githubusercontent.com/6254252/38529108-50fb27dc-3c39-11e8-981e-7a20c5a21eb3.png)
@victorpb, baixei a ultima versão e fiz os testes. Esta OK! Que erro esta sendo gerado nos seus testes?

**Comment by victorpb** [comment]
@Gerley  os erros são do financeiro, inconsistência de valores. Estou usando o Postgres 10.03

![error](https://user-images.githubusercontent.com/4712774/38529646-8da6d656-3c3c-11e8-8c89-ee64538b574e.png)

**Comment by Gerley** [comment]
@victorpb,  Eu fiz os testes com o SQLite3. Por isso que o meu passou.

**Comment by lukasgarcya** [comment]
Pode ser versão do PostgreSQL pois no meu trabalho tivemos um probleminha com uma versão anterior quando fomos atualizar o sistema

**Comment by victorpb** [comment]
Atualizar versão do Postgres é sempre uma merda, to usando a ultima, vou da uma olhada nisso essa semana para entender e ver o que é.

**Comment by Gerley** [comment]
Não tive tempo de verificar os erros. Pelo conteúdo das mensagens, parece que é problema de formatação de numero... A aplicação esta trabalhando com numeros no formato 'pt-br' (ex. 12.234,20) e o banco no formato 'en-us' (ex. 12,234.20), ou vice versa. Mas é apenas uma suposição...

**Comment by lukasgarcya** [comment]
Estou usando o postgresql 9.6.4 e não tive problemas.
Vou atualizar para o 10 e ver o que acontece.

**Comment by lukasgarcya** [comment]
@victorpb quando vc executa este código no Python no seu computador o que retorna?
from decimal import Decimal
import locale
locale.setlocale(locale.LC_ALL, '')
locale.format(u'%.2f', Decimal('120.00'), 1)

**Comment by victorpb** [comment]
@lukasgarcya no pc que fiz os teste so posso executar a noite e te mando o resultado.
Mas possívelmente o problema deve ser o LC_COLLATE do postgres, como o @Gerley falou. Dependendo ele muda a formatação dos tipos double. No projeto django estamos usando o pt-br.
Se for isso no Makefile vou tentar criar uma entrada para criar o banco correto no postgres.

**Comment by victorpb** [comment]
Por padrão sempre crio meus bancos em EN_en, mudando o timezone. Ai os testes não passaram, mas vou verificar isso hoje a noite.

**Comment by lukasgarcya** [comment]
Consegui resolver praticamente todos os erros exceto um. No caso esta no pull request. era o locale.setlocale. Coloquei para pt-br já que o projeto esta usando isto.

**Comment by victorpb** [comment]
Fiz os testes novamente, cirei o banco com o **LC_COLLATE** correto e todos os testes passaram, script abaixo.

CREATE DATABASE nome_da_base
    TEMPLATE=template0
    LC_CTYPE="pt_BR.UTF-8"
    LC_COLLATE="pt_BR.UTF-8";
