### ISSUE TITLE
Imagem no Docker e utilização do docker-compose

### ISSUE THREAD

**Issue by lukasgarcya** [thiagopena/djangoSIGE#29]
Estou criando o Dockerfile e o docker-compose para usar no servidor e gostaria de saber se querem que disponibilizem no projeto.

**Comment by lukasgarcya** [comment]
Pode hospedar no docker hub

**Comment by lukasgarcya** [comment]
@victorpb #31

**Comment by victorpb** [comment]
Valeu @lukasgarcya esse fds vou dar uma olhada em tudo

**Comment by lukasgarcya** [comment]
@Gerley está exigindo que tenha a tag. Quando não tem explícito o docker Pega o latest por padrão então eu não coloco para usar a última. Vou colocar implicitamente

**Comment by Gerley** [comment]
Parece que tem como ignorar esta regra, mas não sei se é uma boa ideia.

https://github.com/hadolint/hadolint/blob/master/README.md

**Comment by lukasgarcya** [comment]
Vou criar outro PR com estas correções.

**Comment by lukasgarcya** [comment]
Problema corrigido.

**Comment by Gerley** [comment]
Parabens @lukasgarcya.
