### ISSUE TITLE
Problema com o Chrome

### ISSUE THREAD

**Issue by douglaspetrin** [thiagopena/djangoSIGE#33]
Boa noite, 

testei no Chrome e não está funcionando corretamente. Algo relacionado a css/js?

Mozilla e IE estão ok.

Acredito que não seja um problema em minha maquina, alguem concorda comigo?

Parabéns pelo projeto!!

**Comment by victorpb** [comment]
E aí @douglaspetrin blz?

Cara aqui uso o Chrome e funciona, tem como mandar um print de como fica a tela?

**Comment by douglaspetrin** [comment]
@victorpb de uma olhada: https://drive.google.com/file/d/1jxm5BXLBjB0ErlogGYDnddCRabTX2sk8/view?usp=sharing

**Comment by thiagopena** [comment]
@douglaspetrin Isso não é problema do Chrome, acredito que não está encontrando alguns arquivos estáticos. Poderia clicar com o botão direito na página, em "Inspecionar" e selecionar a aba "Console" e mostrar os erros que aparecem?

**Comment by douglaspetrin** [comment]
@thiagopena desculpa a demora pra responder. Dei um inspect e nada de erros aparecendo.

Veja o print: https://drive.google.com/file/d/15VR61REU7SQ0w-Lr_2gCGChc_1WoUJCy/view?usp=sharing

**Comment by Gerley** [comment]
Olá @douglaspetrin, na mesma tela que você tirou o print, tem como mostrar a aba "Network" para ver se os arquivos da aplicação foram carregados corretamente?

**Comment by douglaspetrin** [comment]
opa @thiagopena, de uma olhada:

https://drive.google.com/file/d/19IG-GZCHidX_aRaJtrYKMiNlulkHUJFq/view?usp=sharing

estaria faltando o carregamento de materialize.css ?

**Comment by victorpb** [comment]
@douglaspetrin  realmente está faltando os estáticos do materialize.css(ver imagem abaixo)
Verifica por favor se na sua pasta **djangoSIGE/djangosige/static/css/** tem esses [arquivos ](https://github.com/thiagopena/djangoSIGE/tree/master/djangosige/static/css)

![print](https://user-images.githubusercontent.com/4712774/38938267-8431fd06-42fb-11e8-9d80-10d36156bc35.png)

**Comment by douglaspetrin** [comment]
@victorpb sim. Verifiquei e todos arquivos estão na pasta. Se eles não estivessem, o projeto nao rodaria no Mozilla e nem no IE, não concorda?

 Mas nesses navegadores o projeto está rodando ok, por isso iniciei o assunto apontando o Chrome.

Atualizei o Chrome e não mudou nada também.

**Comment by Gerley** [comment]
@douglaspetrin, parece que seus arquivos estão ok! Se tivesse faltando algum arquivo static, iria retornar o erro 404 para alguma chamada. Todos os arquivos solicitados estão retornando codigo 200.

Por alguma razão, que desconheço, parece que o seu Chrome não está conseguindo interpletar o comando "@import url(materialize.css);"  do arquivo "/static/css/style.css".

**Comment by lukasgarcya** [comment]
@Gerley tive alguns problemas com arquivos estáticos aqui em outro projeto no qual por algum motivo os arquivos ficaram com tamanho 0 então não carregava. Os arquivos eram fontes do awesome. Verifica isto.

**Comment by lucaslimabnu** [comment]
Opa,
tenta dar um "python manage.py collectstatic" e em seguida "yes".
pode ser que o Django não tenha mapeado suas statics ;)

**Comment by douglaspetrin** [comment]
@lucaslimabnu, executei o collectstatic e me retornou:

> django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.

mas de qualquer forma, agora está rodando no Chrome. Obrigado!

**Comment by lucaslimabnu** [comment]
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),"static")

Tenta colocar isso no settings.py

**Comment by thiagopena** [comment]
Parece que o problema foi resolvido, fechando a issue...
