### ISSUE TITLE
Usuários só podem visualizar clientes da empresa a que pertencem...

### ISSUE THREAD

**Issue by haokidys** [thiagopena/djangoSIGE#36]
Como impedir de usuários cadastrado em uma empresa, visualizarem os clientes cadastrados por usuários de outra empresa?

**Comment by thiagopena** [comment]
@haokidys você pode fazer a relação de Empresa -> Usuario, ai nas views você checa o usuário logado e faz a filtragem dos clientes na view. O model MinhaEmpresa tem uma relação semelhante.

**Comment by victorpb** [comment]
#36

**Comment by victorpb** [comment]
#16

**Comment by robertowiest** [comment]
Olá, também estou enfrentando o mesmo problema. Porém uma outra solução que vejo seria implementar multi databases. O que você acha? Como poderia fazer isso?

**Comment by thiagopena** [comment]
Fechando por ser uma issue duplicada [#16](https://github.com/thiagopena/djangoSIGE/issues/16)
