### ISSUE TITLE
Ajuda como o Digital Ocean

### ISSUE THREAD

**Issue by haokidys** [thiagopena/djangoSIGE#38]
alguem poderia me ajudar com a configuração do djangoSIGE no digitalocean?

to a varios dias tentando deixar ele online mais sem sucesso.

quando coloco o default.conf no etc/nginx/sites-available e fasso o link simbolico, meu nginx para

alguem poderia me explicar o processo passo a passo, pois ate agora so fiz alguns cursos com aplicativos simples e percebo que o dejangoSIGE é bem robusto e a configuração esta diferente.

é capas dele esta configurado tudo automatizado e eu to deixando passar alguma coisa por falta de conhecimento.

**Comment by victorpb** [comment]
@haokidys  você ta usando o gunicorn? Local você consegue acessar?
da uma olhada no link 
https://danielammorais.com/2016/11/21/deploy-de-app-django-no-nginx/

**Comment by haokidys** [comment]
Vou da uma olhada no tutorial que vc me mandou. no momento mudei as configurações do settings.py mas estou tendo problemas com os arquivos statics. se poder me ajudar com a configuração correta do settings.py

**Comment by victorpb** [comment]
Seta no arquivo de configurações do nginx a pasta static correta

location /static/ {
                alias   {path_project}/djangosige/static/;
         }

**Comment by haokidys** [comment]
ta dizendo que ta ok
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
mais continua sem css parece

ficou online, mais ta todo zuado

**Comment by victorpb** [comment]
@haokidys  Como ta seu location /static?

**Comment by haokidys** [comment]
eu fiz tudo novamente,coloquei o caminho que vc falo, reiniciei tudo. e deu certo.
obrigado pela paciencia.
no momento, esta tudo resolvido.
oque precisar, tamo junto.
