### ISSUE TITLE
Estrutura do projeto, criação e modificações de app

### ISSUE THREAD

**Issue by haokidys** [thiagopena/djangoSIGE#39]
Estou com problema pra entender a estrutura do projeto, já que ele tem vários sub níveis e eu só avia feito projetos mais simples seguindo tutoriais e cursos online.

Alguém poderia me ajudar com o processo de criação de um aplicativo nesse projeto utilizando os níveis corretos?

E se eu precisar desativar um app ou mudar o nome, qual seria o procedimento?

sei que é muita informação, então se alguém poder me auxiliar ficarei muito grato.

Caso alguém me mande ir estudar a documentação do django ou treinar mais apps, é exatamente isso que venho fazendo. mais como a informação é nova, ainda não é natural pra mim, principalmente em um projeto mais complexo e para avançar a gente tem que se desafiar. tmj!

**Comment by victorpb** [comment]
E ai @haokidys  blz? Vi aqui que você criou um repositório desse e não referenciou, isso geralmente não é uma boa prática referenciar o projeto Pai no README ou simplesmente fazer um fork, pois assim já deixa referenciado o projeto Pai.(Só uma dica mesmo) e facilita quando implementa algo novo e manda um Pull Request ajudando outros membros da comunidade também.

Para criar um app novo é só criar na pasta djangosige/apps/ e seguir o padrão do projeto, pasta para os models, views e forms, e dentro dele cada entidade tem seu próprio arquivo e usar o que já está pronto no sistema.

Se puder olhar o app de cadastro verá que ele usa muito herança, então se não tem um conceito bacana de orientação a objeto seria interessante ler um pouco sobre isso e também sobre MVC, [apesar de que para alguns django não é um framework MVC](https://docs.djangoproject.com/pt-br/2.0/faq/general/#django-appears-to-be-a-mvc-framework-but-you-call-the-controller-the-view-and-the-view-the-template-how-come-you-don-t-use-the-standard-names).

Desativar um app ou remover seria só tirar do settings, só tendo cuidado porque ele pode ser dependências de outros apps.

**Comment by victorpb** [comment]
Uma boa coisa também é sempre escrever testes.

**Comment by victorpb** [comment]
@haokidys Mano, 
tamo junto sei como é isso, já quebrei muito a cabeça e tive pessoas que me ajudaram muito, qualquer coisa que eu puder ajudar me manda um email victtor.vpb@gmail.com.

Para fazer o fork é só clicar no botão de fork que ele ja cria um repositorio para você no seu github, da uma olhada nesse [link](https://github.com/UNIVALI-LITE/Portugol-Studio/wiki/Fazendo-um-Fork-do-repositório).

Cara, aprendi muito resolvendo issues em projetos, talvez isso seja uma boa forma de começar pq a galera vai orientando se ta legal ou não o que poderia melhorar. ;)

Qualquer coisa é só falar.

**Comment by haokidys** [comment]
Opa, fiz aqui. vou da uma estudada nas coisa que vc me falo.
gravei seu contanto. oque precisar tb é só falar, tamo junto.

**Comment by victorpb** [comment]
Valeu mando @haokidys
