### ISSUE TITLE
Esqueceu a senha?

### ISSUE THREAD

**Issue by jfcnetto** [thiagopena/djangoSIGE#41]
Olá,

Primeiro meus parabéns, iniciativa muito boa, gostaria de uma ajuda estou fazendo uns estudo e na views.py login enviar e-mail para nova senha esta apresentando a seguinte mensagem:

Reverse for 'trocarsenhaview' with keyword arguments '{'uidb64': b'MQ', 'token': '4yy-dd6d8f5c2e0f19763bfc'}' not found. 1 pattern(s) tried: ['login/trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$']

segue abaixo meus parametros de configração de e-mail.

EMAIL_HOST = 'smtp.sendgrid.net'  

EMAIL_HOST_USER = '********@sendgrid.net'

EMAIL_HOST_PASSWORD = '********'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

Agradeço ajuda
João Neto

**Comment by victorpb** [comment]
@jfcnetto estava chegando o uid como byte no template, convertir para utf-8.

**Comment by jfcnetto** [comment]
Efetuei o teste aqui e ficou Ok!!
