### ISSUE TITLE
Problemas em Deploy com PostgreSQL

### ISSUE THREAD

**Issue by maxthetor** [thiagopena/djangoSIGE#43]
Ao tentar fazer um deploy com o banco postgresql, recebo a seguinte mensagem 
no comando migrate.

SystemCheckError: System check identified some issues:

ERRORS:
cadastro.Categoria: (auth.E005) The permission codenamed 'view_categoria' clashes with a builtin permission for model 'cadastro.Categoria'.
cadastro.Cliente: (auth.E005) The permission codenamed 'view_cliente' clashes with a builtin permission for model 'cadastro.Cliente'.
cadastro.Empresa: (auth.E005) The permission codenamed 'view_empresa' clashes with a builtin permission for model 'cadastro.Empresa'.
cadastro.Fornecedor: (auth.E005) The permission codenamed 'view_fornecedor' clashes with a builtin permission for model 'cadastro.Fornecedor'.
cadastro.Marca: (auth.E005) The permission codenamed 'view_marca' clashes with a builtin permission for model 'cadastro.Marca'.
cadastro.Produto: (auth.E005) The permission codenamed 'view_produto' clashes with a builtin permission for model 'cadastro.Produto'.
cadastro.Transportadora: (auth.E005) The permission codenamed 'view_transportadora' clashes with a builtin permission for model 'cadastro.Transportadora'.
cadastro.Unidade: (auth.E005) The permission codenamed 'view_unidade' clashes with a builtin permission for model 'cadastro.Unidade'.
compras.OrcamentoCompra: (auth.E005) The permission codenamed 'view_orcamentocompra' clashes with a builtin permission for model 'compras.OrcamentoCompra'.
compras.PedidoCompra: (auth.E005) The permission codenamed 'view_pedidocompra' clashes with a builtin permission for model 'compras.PedidoCompra'.
estoque.LocalEstoque: (auth.E005) The permission codenamed 'view_localestoque' clashes with a builtin permission for model 'estoque.LocalEstoque'.
estoque.MovimentoEstoque: (auth.E005) The permission codenamed 'view_movimentoestoque' clashes with a builtin permission for model 'estoque.MovimentoEstoque'.
financeiro.Lancamento: (auth.E005) The permission codenamed 'view_lancamento' clashes with a builtin permission for model 'financeiro.Lancamento'.
financeiro.PlanoContasGrupo: (auth.E005) The permission codenamed 'view_planocontasgrupo' clashes with a builtin permission for model 'financeiro.PlanoContasGrupo'.
fiscal.GrupoFiscal: (auth.E005) The permission codenamed 'view_grupofiscal' clashes with a builtin permission for model 'fiscal.GrupoFiscal'.
fiscal.NaturezaOperacao: (auth.E005) The permission codenamed 'view_naturezaoperacao' clashes with a builtin permission for model 'fiscal.NaturezaOperacao'.
fiscal.NotaFiscalEntrada: (auth.E005) The permission codenamed 'view_notafiscalentrada' clashes with a builtin permission for model 'fiscal.NotaFiscalEntrada'.
vendas.CondicaoPagamento: (auth.E005) The permission codenamed 'view_condicaopagamento' clashes with a builtin permission for model 'vendas.CondicaoPagamento'.
vendas.OrcamentoVenda: (auth.E005) The permission codenamed 'view_orcamentovenda' clashes with a builtin permission for model 'vendas.OrcamentoVenda'.
vendas.PedidoVenda: (auth.E005) The permission codenamed 'view_pedidovenda' clashes with a builtin permission for model 'vendas.PedidoVenda'.

**Comment by victtorvpb** [comment]
@maxthetor tá uma olhada na issue #42

**Comment by marcosjuniorpr** [comment]
Conseguiu corrigir o erro?

**Comment by rg3915** [comment]
Criei um [PR #3](https://github.com/thiagopena/djangoSIGE/pull/44) que corrige isso.

**Comment by maxthetor** [comment]
deu certo. no arquivo requirements.txt , coloquei:
django==2.0

**Comment by rg3915** [comment]
@maxthetor vc não usou a versão mais recente do Django... mas tudo bem.
