### ISSUE TITLE
Erro de comunicação

### ISSUE THREAD

**Issue by robertowiest** [thiagopena/djangoSIGE#50]
Olá, estou com o seguinte erro ao tentar fazer um teste de comunicação com o SEFAZ

`

Request Method: | POST
-- | --
http://127.0.0.1:8000/fiscal/notafiscal/consultarcadastro/
2.1.3
ConnectionResetError
[Errno 54] Connection reset by peer
/Users/robertow/.pyenv/versions/3.5.0/lib/python3.5/ssl.py in do_handshake, line 628
/Users/robertow/.pyenv/versions/3.5.0/bin/python3.5
3.5.0

`

**Comment by jfcnetto** [comment]
Nos testes que executei apresenta mensagem de que a senha do certificado digital esta incorreta, porem o mesmo certificado com a mesma senha funcionou em  outras aplicações,

**Comment by jfcnetto** [comment]
Bom acho que deve ser feita a homologação na SEFAZ DF, no meu caso, será que alguém sabe os procedimento para isso?

**Comment by jfcnetto** [comment]
Bom acho que deve ser feita a homologação na SEFAZ DF, no meu caso, será que alguém sabe os procedimento para isso?

**Comment by victtorvpb** [comment]
Galera, o sistema não estar portado para o leiaute 4.0 da NF-e e se não me engano o leiaute 3.0 ja não está mais disponível.

**Comment by jfcnetto** [comment]
Ok porem para para NF-c também não esta ok!!

**Comment by victtorvpb** [comment]
Acho que a NFC-e 3.0 que é a do projeto TB já foi desativada. E preciso
migrar o projeto para a versão 4.0.

Em qua, 12 de dez de 2018 23:08, jfcnetto <notifications@github.com
escreveu:

**Comment by thiagopena** [comment]
Fechando a issue (Duplicate of #34 ), o suporte para as novas versões sairá provavelmente mais tarde esse ano. Mantenho todos atualizados.
Como disse o @victtorvpb , o suporte tem que ser adicionado inicialmente no [PySIGNFe](https://github.com/thiagopena/PySIGNFe), estou trabalhando nisso, assim que concluir implemento para o SIGE, que é algo mais simples.
