### ISSUE TITLE
Dúvida com os passos 2 e 3

### ISSUE THREAD

**Issue by alexandreag82** [thiagopena/djangoSIGE#51]
Boa noite!!

Como efetuar os passos 2 e 3?

Edite o conteúdo do arquivo djangosige/configs/configs.py

Gere um .env local

**Comment by alexandreag82** [comment]
Questão resolvida, eu consegui abrir a aplicação!!!

Obrigado!!

**Comment by victtorvpb** [comment]
@alexandreag82  para fazer isso é só se vc quiser sobescrever alguma configuração do django que já esta lá, se for para rodar o projeto é só rodar 

python contrib/env_gen.py
