### ISSUE TITLE
Problema com novos urls

### ISSUE THREAD

**Issue by jfcnetto** [thiagopena/djangoSIGE#55]
Olá,
estou fazendo um teste com novo rrelatorio no modulo venda para gerar um contrato de compra e venda porem apresenta um erro somnte em produção no ambinte de desenvolvimento esta ok, 
alterei urls.py , a view vendas.py,__init__.py (cendas/views)  e pedido_venda_edit.html.

esta e a mensagem de erro:

"Reverse for 'gerarpdfpedidovenda2' not found. 'gerarpdfpedidovenda2' is not a valid view function or pattern name."

Alguém pode me ajudar?

Grato,

João

**Comment by thiagopena** [comment]
@jfcnetto você provavelmente modificou os templates e adicionou uma url no formato: `{% url 'vendas:gerarpdfpedidovenda2' %}` e não adicionou esse mapeamento de url no código apontando para uma view.
