### ISSUE TITLE
erro ao cadastrar o certificado digital

### ISSUE THREAD

**Issue by joseliobeze** [thiagopena/djangoSIGE#56]
ponent (C:\Users\jbs\Downloads\djangoSIGE-master\djangoSIGE-master\djangosige\media\)
Bad Request: /fiscal/notafiscal/configuracaonotafiscal/
![erro do cerificado](https://user-images.githubusercontent.com/42746392/53579697-ce8cb700-3b58-11e9-9347-cef1c69db166.png)

**Comment by thiagopena** [comment]
@joseliobeze não consegui recriar esse problema, poderia passar mais detalhes ou se conseguiu resolvê-lo? Obrigado

**Comment by thiagopena** [comment]
Fechando a issue, caso haja alguma atualização avise @joseliobeze !
