### ISSUE TITLE
produção 

### ISSUE THREAD

**Issue by josetiagobispo** [thiagopena/djangoSIGE#57]
alguém sabe como coloco em produção python manage.py runserver sem ser o endereço 127.0.0.1:8000 mudar para meuipexterno:8000

**Comment by claysllanxavier** [comment]
Olá @josetiagobispo, vc pode utilizar o seguinte comando: **python manage.py runserver 0.0.0.0:8000**

Com isso ele vai permitir que outras pessoas acessem seu ip pela porta 8000

**Comment by ficosta** [comment]
@josetiagobispo  O correto para rodar em produção é utilizar algum servidor web, como (nginx ou apache) + gunicorn. O runserver inicia um servidor apenas para desenvolvimento e nao deve ser utilizado em produção.
Vc pode ver esse guia bem legal: https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-18-04

@thiagopena  #close

**Comment by thiagopena** [comment]
fechando issue... obrigado @ficosta
