### ISSUE TITLE
Criar db_backup.json

### ISSUE THREAD

**Issue by HigorMonteiro** [thiagopena/djangoSIGE#6]
@thiagopena talvez seria legal vc criar um `db_backup.json` do seu banco de teste para que não quemos perdendo tempo inserindo dados na hora de fazer testes , no **Makefile** eu deixei um comando que auxilia essa tarefa .

**Comment by thiagopena** [comment]
Pode deixar. Infelizmente tive que refazer a base de dados do zero ao upar o projeto, e não deu tempo ainda de recria-la, mas monto uma de teste rápido hoje mais tarde. Se tiver um XML de NF-e pode importar em Fiscal > Nota Fiscal > Notas Fiscais > Importar Nota, que ele já cria os produtos, pedidos de venda, grupos fiscais, etc, da própria nota. Esta funcionalidade precisa de mais testes ainda, mas é possível se estiver com muita pressa.

**Comment by HigorMonteiro** [comment]
Muito bom brother, acho que ainda manjo um pouco dessa parte, um tempo atrás trabalhei com suporte e via um pouco disso, quanto aos teste, podemos já ir vendo o uso de TDD, vou ver se crio alguns testes, pois ainda estou aprendendo rsrs .

**Comment by thiagopena** [comment]
Seria ótimo desenvolver testes, sei que fica complicado com o projeto já avançado.

**Comment by HigorMonteiro** [comment]
vamos procurar a melhor maneira e postamos aqui . exemplo : podemos ir fazendo uma ` APP `por vez .

**Comment by thiagopena** [comment]
Vamos sim, o que dificulta escrever testes é que o projeto se baseia bastante em html e nos códigos em javascript, mas facilitaria muito a vida testar a criação e edição dos objetos quando for feita alguma modificação nos modelos do app, porque eu acho que a estrutura da base de dados pode ser melhorada ainda. Acho melhor começar os testes pelo cadastro.

**Comment by lukasgarcya** [comment]
Pode usar o http://phantomjs.org/. Uso o https://splinter.readthedocs.io/en/latest/ que posso escolher qual navegador usar. No servidor uso o google-chrome com xvfb.

**Comment by thiagopena** [comment]
sim @lukasgarcya , mas antes seria melhor concluir os testes para o Backend, e depois começar a pensar em desenvolver testes para o JS. Se tiver experiência com o phantomjs, agradeceria uma ajuda no desenvolvimento de testes de JS, pois por enquanto nada do código JS está testado.

**Comment by lukasgarcya** [comment]
Com o splinter tenho uma camada onde posso escolher qual teste, tal como django, phantomjs, navegador. Não muda os testes apenas a instância do browser que altero.
