### ISSUE TITLE
Permissões 

### ISSUE THREAD

**Issue by brunomaffei** [thiagopena/djangoSIGE#62]
Galera tudo bom? Estou vendo as permissões aqui não estão aparecendo. Alguém poderia me ajudar ou informar o que esta de errado?  vlw muito obrigado

**Comment by thiagopena** [comment]
@brunomaffei você executou os comandos `python manage.py makemigrations`  e  `python manage.py migrate`?

**Comment by rafaelrbnet** [comment]
TOP funciona

**Comment by thiagopena** [comment]
Fechando a issue, parece que o migrate já resolve
