### ISSUE TITLE
Parabéns ao projeto !

### ISSUE THREAD

**Issue by toninhonunes** [thiagopena/djangoSIGE#72]
Thiago,

Você é o criador do projeto? Se for parabéns, muito boa sua iniciativa e analisando o código separou bem o models.

Estou começando a projetar um sistema que já possuo, mas é um segmento bem diferente do seu. O seu projeto atual separa por empresa a modelagem? Hoje o meu sistema legado é uma cópia para cada cliente em separado, como dá muita manutenção, quero usar um recurso como multi-tenance para sincronizar tudo de uma vez quando ocorrer upgrades.

Cordialmente,

Antonio Carlos

**Comment by thiagopena** [comment]
Boa noite @toninhonunes , ele separa a permissão por usuário, um usuário administrador pode gerenciar essas permissões pela própria interface.

Agradeço as parabenizações!
