### ISSUE TITLE
Senha de acesso ao SIGE

### ISSUE THREAD

**Issue by LeonSoft2000** [thiagopena/djangoSIGE#78]
Prezados

Na tela da aplicação qual o usuário e a senha do primeiro acesso ?

**Comment by rafaelrbnet** [comment]
Vc precisa criar o usuário admin através da linha de comando.

Python manager.py createsuperuser
 Da uma olhada lá no tutorial

Em qui, 14 de nov de 2019 02:31, LeonSoft2000 <notifications@github.com>
escreveu:

**Comment by LeonSoft2000** [comment]
Deu certo, muito obrigado.. é que nao achei o tutorial..

**Comment by rafaelrbnet** [comment]
Show

Em qui, 14 de nov de 2019 10:21, LeonSoft2000 <notifications@github.com>
escreveu:
