### ISSUE TITLE
Já esta implementado a NFe 4

### ISSUE THREAD

**Issue by paulosix** [thiagopena/djangoSIGE#79]
Bom dia senhores,

alguem sabe informar e o projeto já esta gerando na nfe 4 ? se não o que esta  faltando (@thiagopena ) para impemtementar ? posso ajudar ? em que posso ajudar ?

grato 
Paulo

**Comment by JacksonOsvaldo** [comment]
Atualmente, a aplicação ainda não está com o ambiente para emissão no 4.0. está rodando sobre o modelo antigo. Também concordo que precisamos mudar e/ou implementar isso na aplicação.

**Comment by victtorvpb** [comment]
Pessoal acompanhar a issue #34
