### ISSUE TITLE
erro ao executar a aplicação

### ISSUE THREAD

**Issue by Matheus-Thurler** [thiagopena/djangoSIGE#83]
Relatei erro da aplicação nos arquivos em html da pasta templates, solução é trocar todos os:
{% load staticfiles %}
{% load static from staticfiles %}
{% load adminstatic %}
 para somente :
 {% load static %}

Essas tags foram preteridos no Django 2.1 e removidos no Django 3.0 . Pelo visto atualizaram para a versão que está em uso. Espero ter ajudado.

**Comment by rg3915** [comment]
https://github.com/thiagopena/djangoSIGE/commit/5676c708b2aabcac8b5bec4fdfd354842100c860
