### ISSUE TITLE
Multiplos Usuários

### ISSUE THREAD

**Issue by PedroPCardoso** [thiagopena/djangoSIGE#94]
O que seria necessario para fazer a implementação para multiplos usuários, com informações separadas para cada um que pertencesse a determinada empresa ?

**Comment by nilton-medeiros** [comment]
@PedroPCardoso, você quis dizer múltipla empresas ao invés de múltiplos usuários, pois múltiplos usuários ele já é, certo?

**Comment by PedroPCardoso** [comment]
Isso, eu acabei utilizando o django-tenant-schemas, apliquei no projeto para poder utilizar o projeto da forma que precisava.
