### ISSUE TITLE
Atualizar o README

### ISSUE THREAD

**Issue by nilton-medeiros** [thiagopena/djangoSIGE#95]
Muitos iniciantes em Django estão apanhando para instalar o aplicativo, fiz um passo-a-passo da instalação funcional, queira considerar por favor. Está no README.txt anexo.
[README.txt](https://github.com/thiagopena/djangoSIGE/files/5576666/README.txt)

**Comment by rg3915** [comment]
Gostei da sua sugestão @nilton-medeiros coloquei no README do projeto. Valeu.
